name = "top_ten_game/ada_price_guess"
version = "0.0.0"
compiler = "v1.1.17"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'top_ten_game/ada_price_guess'"

[repository]
user = "top_ten_game"
project = "ada_price_guess"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[config]
